### PR TITLE
Fix SV not raising error when not fitted

### LINKED ISSUE #193: Better error message when SuperVectorizer's transform method is called before fit
Scikit-learn has a mechanism to check that an estimator is fitted, and if not raise a good error message. We should use it.

### PR DESCRIPTION
**Pull request by LilianBoulard**
Fixes #193

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Can we add a test that fails without this PR, so that we don't fall back to the same problem after a refactoring.

**Comment by LilianBoulard** [comment]
Done, although I think it should get addressed by #164

**Comment by GaelVaroquaux** [comment]
We have a failing test.

Maybe we can skip for old versions of scikit-learn (if this is the source of the problem).

**Comment by LilianBoulard** [comment]
Found a workaround for older versions by passing all the attributes of the object.
Not sure it's the way the function is supposed to be used, the docstring doesn't say much more, but the test should be passing :)

**Comment by GaelVaroquaux** [comment]
LGTM. Merging. Thanks

**Pull request merged**
