### PR TITLE
DOC enable toc in example sidebars

### PR DESCRIPTION
**Pull request by pierreglaser**

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I had disabled it because I liked the lighter design :). I'm open to
discussion, but it is hard to keep a fixed sidebar (as opposed to
scrolling) and the toc: it tends to create a too high sidebar.

**Comment by pierreglaser** [comment]
Yes I figured it was voluntary. The example in #90 is pretty long, that is why I wanted to enable it. 
I add a toc in the main body instead.

**Comment by GaelVaroquaux** [comment]
Adding a table in the body seems right. I was about to suggest it, but wanted to hear your thoughts. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
This should be closed, shouldn't it?

**Comment by pierreglaser** [comment]
yes. closing

**Pull request closed without merging**
