### PR TITLE
fix circleCI doc building

### LINKED ISSUE #447: CircleCI failing to build docs
It seems that the tests are failing due to a CircleCI error when [installing miniconda](https://app.circleci.com/pipelines/github/dirty-cat/dirty_cat/1353/workflows/05f190d6-36c6-4a01-954f-38c33f634482/jobs/2875).

Still trying to understand why.

### PR DESCRIPTION
**Pull request by LeoGrin**
Fix #447 

Using the fix from https://github.com/ContinuumIO/anaconda-issues/issues/13110 works. What I'm not sure is why it only appeared now.

Once this is merged, tests on failing PRs should be relaunched.

### CODE REVIEW

**Review by GaelVaroquaux — APPROVED** [review]
Looks good to me. Thanks a lot!

I'll let it open for others to look (eg @LilianBoulard ) and see if they have comments. If no comments, I'll merge.

**Review by jovan-stojanovic — APPROVED** [review]
Great, thanks!

**Comment by GaelVaroquaux** [comment]
Merging. Thanks!

**Comment by LilianBoulard** [comment]
That's a strange issue! Thanks for the fix!

**Pull request merged**
