### PR TITLE
Support paths as strings in public fetching API

### PR DESCRIPTION
**Pull request by LilianBoulard**
- Adds support for paths as strings in the public fetching API
- Uses cleaner temporary directories in the fetching test

### CODE REVIEW

**Comment by LilianBoulard** [comment]
Changelog entry taken care of by #432

**Review by jovan-stojanovic — COMMENTED** [review]
It seems there is a problem with the fetch_openml function and the temporary directory where you store downloaded files..

**Comment by GaelVaroquaux** [comment]
Darn, there are test failures, and they seem related to this PR

**Comment by LilianBoulard** [comment]
Yes, and it's system-specific, which is very annoying to debug... I'll try and tackle that today

**Pull request merged**
