### PR TITLE
MAINT Format the code-base to be `pre-commit` compliant

### PR DESCRIPTION
**Pull request by jjerphan**
Follow-up of #308 and #317.

This applies the `pre-commit` formatting on the whole code-base

A few docstrings lines were exceeding the column limit but we're hardly breakable. I chose to put a `# noqa` directive so that black ignore them; but there might be a better solution (such as defining custom types and using them in the docstring if it makes sense).

A follow-up PR will add a `.git-blame-ignore-revs` file not to have the formatting disrupt `git blame` with some documentation to have it setup, see [scikit-learn's](https://github.com/scikit-learn/scikit-learn/blob/main/.git-blame-ignore-revs).

### CODE REVIEW

**Comment by jjerphan** [comment]
I think the failure on CodeCov regarding the [Relative Coverage](https://docs.codecov.com/docs/codecov-delta#relative) (76.24% which does not meet the target of 85.33%) can be ignored due to the nature of this PR.

**Comment by jjerphan** [comment]
@GaelVaroquaux and @LilianBoulard: this PR can be reviewed.

**Review by GaelVaroquaux — APPROVED** [review]
LGTM (fingers crossed that this doesn't create too much of a mess). Merging

**Comment by jjerphan** [comment]
Thanks.

#325 has been opened, and once it's merged the entire setup is done.

**Pull request merged**
