### PR TITLE
Enable testing on GitHub actions

### PR DESCRIPTION
**Pull request by NicolasGensollen**
See #171 

This PR proposes to run tests on Github actions.
Note: I've used the structure we use for Nilearn but I can adapt if needed.

### CODE REVIEW

**Comment by NicolasGensollen** [comment]
@LilianBoulard it looks like the tests don't run with minimum dependencies (I used the ones from the README). 
Do you know if these were tested before? 
Note: I tried bumping to numpy==1.16, scipy==1.2, and sklearn==0.20 and it runs better

**Comment by LilianBoulard** [comment]
Hi @NicolasGensollen  

Just checked on a prior PR that used Travis, and while there is a worker that is supposed to launch the tests with the minimal dependencies, there was a misconfiguration with it, and he did not 😅.
See https://travis-ci.org/github/dirty-cat/dirty_cat/jobs/760701080 and https://travis-ci.org/github/dirty-cat/dirty_cat/jobs/760701079

@GaelVaroquaux what version do you reckon we should bump the minimal dependencies to ?
Perhaps `numpy==1.16`, `scipy==1.2`, and `sklearn==0.20` as suggested by Nicolas ?

**Comment by LilianBoulard** [comment]
Thanks for launching the tests again, looks like it's working this time, though there is a small error with the `GapEncoder`.  
@alexis-cvetkov, could you please have a look ?

**Comment by alexis-cvetkov** [comment]
I was able to reproduce the error on a local environment. I am comparing two outputs that should be the same (or at least almost equal) but for some reason on the "minimal requirements" environment they are not exactly identical but very close (the max absolute / relative error is 1e-12 / 1e-16).
For such cases we can use the function `np.testing.assert_almost_equal` that check if two inputs are equal up to a desired precision (by default 1e-7). We use it in other tests and I think we can simply use that instead. I am pushing this.

**Comment by GaelVaroquaux** [comment]
> For such cases we can use the function np.testing.assert_almost_equal that check if two inputs are equal up to a desired precision (by default 1e-7). We use it in other tests and I think we can simply use that instead.

+1

**Review by GaelVaroquaux — CHANGES_REQUESTED** [review]
Looks great!

One remaining thing: to update the version numbers in the readme

**Review by GaelVaroquaux — APPROVED** [review]
:heart:

Merging. Thanks!!

**Pull request merged**
