### PR TITLE
[WIP] Try to add "Dirty cat" to the page titles

### PR DESCRIPTION
**Pull request by GaelVaroquaux**
This is useful for instance social-media links

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
Not working so far

**Comment by GaelVaroquaux** [comment]
I believe that this is now ready to go

**Comment by GaelVaroquaux** [comment]
A follow up on #173

**Review by LilianBoulard — APPROVED** [review]

**Comment by GaelVaroquaux** [comment]
Thanks for the review @LilianBoulard . Merging

**Pull request merged**
